### ISSUE TITLE
Error on Cmd+shift+c

### ISSUE THREAD

**Issue by natew** [flintjs/flint-atom#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.2
**Thrown From**: [flint](https://github.com/flintjs/flint-atom) package, v3.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'x' of undefined

```
At /Users/nw/.atom/packages/flint/lib/colorPicker/ColorPicker-view.coffee:295

TypeError: Cannot read property 'x' of undefined
  at Object.open (/Users/nw/.atom/packages/flint/lib/colorPicker/ColorPicker-view.coffee:295:32)
  at atom-text-editor.<anonymous> (/Users/nw/.atom/packages/flint/lib/colorPicker/ColorPicker.coffee:43:18)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
  7x -0:59.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:58.2.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:57.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:56.2.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -0:46.6.0 core:move-up (atom-text-editor.editor.is-focused)
 10x -0:45.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:35.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:35 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:34.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  6x -0:31.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:12.7.0 color-picker:open (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.4.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "nuclide-hack",
      "nuclide-click-to-symbol",
      "nuclide-code-format",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-flow",
      "nuclide-hg-repository",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-ssh-dialog",
      "nuclide-tabs",
      "nuclide-type-hint",
      "welcome",
      "highlight-line",
      "bookmarks",
      "spell-check",
      "autocomplete-snippets",
      "autoflow",
      "background-tips",
      "autosave",
      "line-ending-selector",
      "about",
      "deprecation-cop",
      "metrics",
      "release-notes",
      "language-perl",
      "archive-view",
      "vim-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "an-color-picker"
    ]
  },
  "flint": {
    "preferredFormat": "HEX",
    "abbreviateValues": true
  }
}
```

### Installed Packages

```coffee
# User
custom-title, v1.0.1
emmet, v2.3.14
flint, v3.7.0
highlight-selected, v0.10.1
language-babel, v2.3.1

# Dev
No dev packages
```

**Comment by knightli** [comment]
on a color also throw this error
