### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by fkysly** [flintjs/flint-atom#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [flint](https://github.com/flintjs/flint-atom) package, v3.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'x' of undefined

```
At /Users/matianyi/.atom/packages/flint/lib/colorPicker/ColorPicker-view.coffee:300

TypeError: Cannot read property 'x' of undefined
    at Object.open (/Users/matianyi/.atom/packages/flint/lib/colorPicker/ColorPicker-view.coffee:300:32)
    at atom-text-editor.<anonymous> (/Users/matianyi/.atom/packages/flint/lib/colorPicker/ColorPicker.coffee:43:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:47.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:47 core:move-right (atom-text-editor.editor.is-focused)
     -2:46.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:45.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:43.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:40.9.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:52.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:19 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "flint": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
flint, v3.10.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by knightli** [comment]
+1

**Comment by ncammarata** [comment]
looking at this today
